---
trust-domain: "mozilla"
task-priority: low

taskgraph:
  cached-task-prefix: "mozilla.v2.build-mar"
  repositories:
    build_mar:
      name: "build-mar"

workers:
  aliases:
    images:
      provisioner: '{trust-domain}-t'
      implementation: docker-worker
      os: linux
      worker-type: 'linux-docker'
    linux:
      provisioner: '{trust-domain}-t'
      implementation: docker-worker
      os: linux
      worker-type: 'linux-docker'
